name = "hyposelenia"
description = "Simple Web Framework for Hoomans"
version = "0.0.1"
licenses = ["MIT"]
repository = { type = "github", user = "chwrryroll", repo = "hyposelenia" }
gleam = ">= 1.14.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
